### ISSUE TITLE
In index.js fs.writeFile, callback in not optional anymore

### ISSUE THREAD

**Issue by willypuzzle** [trescenzi/transvueify#3]
In index.js fs.writeFile, callback in not optional anymore in node 10. I had to modify manually the code in order to build my code.

For example:

```
fs.writeFile(outputPath, outFile, (err) => {
          if (err) throw err;
          console.log('The file has been saved!');
});
```

Without callback it throws an exception.

**Comment by trescenzi** [comment]
Great catch thanks for filing! I've released `0.0.5` with a fix for this and better error reporting.
